---
title: |
  | \vspace{0.3cm} \Huge \singlespacing \textbf{Economic Data 2023 - Labs}  \vspace{0.28cm}
  | \vspace{0.3cm} \large Week 1 \vspace{0.3cm}
indent: true
output:
  pdf_document:
    number_sections: true
    fig_caption: true
    citation_package: natbib 
    # keep_tex: true
citecolor: blue
linkcolor: blue
bibliography: library.bib
biblio-style: apsr
link-citations: true
fontsize: 11pt
# geometry: margin=3cm
# geometry: margin=2.4cm
geometry: margin=2.45cm
# fontsize: medium
linestretch: 2.5
header-includes:
   - \usepackage{setspace}\setstretch{2.9}
   - \usepackage{caption}
   - \captionsetup[figure]{font=small}
   - \usepackage[font={scriptsize,it}, labelfont={bf}]{caption}
   - \usepackage{threeparttable}
   - \usepackage{booktabs}
   - \usepackage{mathtools}
   - \pagenumbering{gobble}
   - \usepackage{setspace}
   - \usepackage{amsmath}
   - \usepackage{lmodern}
   - \usepackage{bbm}
   - \usepackage{lscape}
   - \newcommand{\blandscape}{\begin{landscape}}
   - \newcommand{\elandscape}{\end{landscape}}
   - \usepackage{boldline}
   - \usepackage{pdfpages}
   - \usepackage{color}
   - \usepackage{xcolor}
   - \colorlet{Blue}{blue}
   - \usepackage{enumitem}
   - \usepackage{romannum}
   - \usepackage{siunitx}
   - \usepackage{gensymb}
   - \usepackage[osf]{mathpazo}
   - \usepackage{graphicx}
   - \newcommand{\indep}{\rotatebox[origin=c]{90}{$\models$}}
   - \newtheorem{theorem}{Definition}
   - \usepackage{indentfirst}
   - \usepackage{pgf,tikz}
   - \usetikzlibrary{shapes}
   - \usepackage{bm}
   - \usepackage{dirtytalk}
   - \setlength{\bibsep}{3pt}
editor_options:
  chunk_output_type: console
---

\onehalfspacing
\pagenumbering{arabic}

# Goals for this lab

\noindent In your first lab the goal is to:

- Familiarize ourselves with the software and platforms used in this unit.

- Create the first chart in Microsoft Excel.

- Insert the chart in Microsoft Word and submit the document on Eduflow




# What you should do before the lab session

- Because this is your very first lab, we do not expect you to prepare anything for this lab.

- In future weeks you will discover that the level of preparation is up to you. The more prepared you are, the better questions can you ask and the more feedback you will get






# 3 What happens in the lab

## Part 1

\noindent A member of the teaching team will go through the points below. Another member will be available for individual support.

- We record attendance.

- We will show you where to find the things on Blackboard, including other resources like the introduction to Microsoft Excel.

- We download and install Microsoft Excel, R, and RStudio.

- We create a chart in Microsoft Excel using data from the Maddison Project Database.

- We insert the chart in a word document. Comment on the chart in at most 50 words and submit it as a test project on eduflow.

<!-- - We give peer feedback on eduflow. -->




## Part 2

\noindent In the second part you will work on your own to finalise the steps above and both members of the teaching team will be available for individual support.










